version: '3.8'
services:
  db-pdv:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: amordeshake_local
    ports:
      - "5432:5432"
    volumes:
      - pdv_data:/var/lib/postgresql/data

volumes:
  pdv_data: